### PR TITLE
Fix arghandling, put test files in build directory

### LINKED ISSUE #28: Termux-elf-cleaner errors if arguments are passed in certain order
Termux-elf-cleaner currently errors if order of passed argument is not the same as it parses them, https://github.com/termux/termux-elf-cleaner/actions/runs/7226804413 failed with: `open("--quiet"): No such file or directory` for example. 

Order shouldn't matter so we have to change how we parse the args. argmatch function that we currently use was taken from emacs, and emacs solves this by sorting argv before parsing. We could go down that route, or change to some other arg parsing system.

### PR DESCRIPTION
**Pull request by Grimler91**
Switch to getopt_long instead of our own arghandling. One side-effect is that options like `-quiet -dry-run` (with just one dash) will no longer work.

Also fix bug for api 21 where file would be modified even with --dry-run. 

Fixes termux/termux-elf-cleaner#28

### CODE REVIEW

File: elf-cleaner.cpp [hunk 1]
```diff
@@ -297,49 +311,77 @@ int parse_file(const char *file_name)
...
+		{"api-level", required_argument, NULL, 'a'},
+		{"dry-run", no_argument, &dry_run, 1},
+		{"jobs", required_argument, NULL, 'j'},
+		{"quiet", no_argument, &quiet, 1},
+		{"help", no_argument, NULL, 'h'},
+		{"version", no_argument, NULL, 'v'},
+		{0, 0, 0, 0}
+	};
+
+	while (1)
```
Comment (thunder-coding) [inline elf-cleaner.cpp:328]: nitpick: s/1/true/

**Review by thunder-coding — APPROVED** [review]
lgtm
